syntax = "proto3";

package accounting.coa.acct;

import 'google/protobuf/empty.proto';
import 'product/accounting/coa/account/product.accounting.coa.account.common.grpc.proto';

service Account {
  rpc Create(common.CoaAccountCreateRequest) returns (common.CoaAccountCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (common.CoaAccountReadAllResponse);
  rpc ReadByID(common.CoaAccountReadByIDRequest) returns (common.CoaAccountReadByIDResponse);
  rpc UpdateOne(common.CoaAccountUpdateOneRequest) returns (common.CoaAccountUpdateOneResponse);
  rpc DeleteOne(common.CoaAccountDeleteOneRequest) returns (common.CoaAccountDeleteOneResponse);
}
