syntax = "proto3";

package accounting.coa.acct.common;

import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/project/enterprise.organization.project.common.grpc.proto';

//###########################################################################
message CoaAccountCreateRequest {
  optional string reference = 1;
  string organization = 2;
  string project = 3;
  optional string parent = 4;
  int32 code = 5;
  string name = 6;
  optional string description = 7;
}

message CoaAccountCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaAccountAll data = 4;
}
//###########################################################################
message CoaAccountReadByIDRequest {
  string id = 1;
}
message CoaAccountReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaAccountAll data = 4;
}
//###########################################################################
message CoaAccountReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGCoaAccountAll data = 4;
}
//############################################################################################
message CoaAccountUpdateOneRequestQuery {
  string id = 1;
}

message CoaAccountUpdateOneRequestSet {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  optional string parent = 4;
  int32 code = 5;
  string name = 6;
  optional string description = 7;
  bool status = 8;
}

message CoaAccountUpdateOneRequest {
  CoaAccountUpdateOneRequestQuery query = 1;
  CoaAccountUpdateOneRequestSet set = 2;
}
message CoaAccountUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaAccountAll data = 4;
}
//############################################################################################

message CoaAccountDeleteOneRequestOption {
  optional bool force = 1;
}

message CoaAccountDeleteOneRequestQuery {
  string id = 1;
}

message CoaAccountDeleteOneRequest {
  CoaAccountDeleteOneRequestQuery query = 1;
  optional CoaAccountDeleteOneRequestOption option = 2;
}
message CoaAccountDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaAccountAll data = 4;
}
//############################################################################################
//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################

message IGCoaAccount {
  optional string id = 1;
  optional string reference = 2;
  optional string organization = 3;
  optional string project = 4;
  optional string parent = 5;
  int32 code = 6;
  string name = 7;
  optional string description = 8;
  optional SysTime time_created = 9;
  optional SysTime time_updated = 10;
  optional SysTime time_deleted = 11;
  bool status = 12;
}

message IGCoaAccountAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  organization.common.EnterpriseOrganization organization = 3;
  project.common.EnterpriseOrganizationProject project = 4;
  optional IGCoaAccountAll parent = 5;
  int32 code = 6;
  string name = 7;
  optional string description = 8;
  optional SysTime time_created = 9;
  optional SysTime time_updated = 10;
  optional SysTime time_deleted = 11;
  bool status = 12;
}