

syntax = "proto3";

package parking.ticket;

service Ticket {
  rpc Create(ParkingTicketCreateRequest) returns (stream ParkingTicketCreateResponse);
  rpc ReadAll(ParkingTicketReadRequest) returns (stream ParkingTicketReadResponse);
  rpc ReadByTicketNumber(ParkingTicketReadByTicketNumberRequest) returns (stream ParkingTicketReadResponse);
}
//##################################################################################

message ParkingITicketTimeBase {
  optional int64 unix = 1;
  optional string humanize = 2;
}

message ParkingITicket {
  optional string id = 1;
  optional string gate = 2;
  optional string ticket_number = 3;
  optional ParkingITicketTimeBase time_created = 4;
  optional ParkingITicketTimeBase time_updated = 5;
  optional bool status = 6;
}
//##################################################################################
message ParkingTicketCreateRequest {
  optional string gate = 2;
  optional string ticket_number = 3;
}

message ParkingTicketCreateResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  optional ParkingITicket data = 4;
}
//##################################################################################
message ParkingTicketReadResponseMetadata {
  optional int64 count = 1;
}
message ParkingTicketReadResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  repeated ParkingITicket data = 4;
  optional ParkingTicketReadResponseMetadata metadata = 5;
}

message ParkingTicketReadRequestOptions {
  optional int32 limit = 1;
  optional bool allowDiskUse = 2;
}

message ParkingTicketReadRequest {
  optional ParkingTicketReadRequestOptions options = 2;
}
//##################################################################################
message ParkingTicketReadByTicketNumberRequest {
  optional string ticket_number = 1;
}
//##################################################################################