syntax = "proto3";

package merchant.contact;

import 'google/protobuf/empty.proto';
import 'product/lms/merchant/contact/product.lms.merchant.contact.common.grpc.proto';


service Contact {
  rpc Create(common.IGMerchantContact) returns (stream common.MerchantContactCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (stream common.MerchantContactReadAllResponse);
  rpc ReadByID(common.MerchantContactReadByIDRequest) returns (stream common.MerchantContactReadByIDResponse);
  rpc UpdateOne(common.IGMerchantContact) returns (stream common.MerchantContactUpdateOneResponse);
  rpc DeleteOne(common.MerchantContactDeleteOneRequest) returns (stream common.MerchantContactDeleteOneResponse);
}