syntax = "proto3";

package merchant.contact.common;

import 'core/account/account.common.grpc.proto';

message IGMerchantContactGeo {
  string latitide = 1;
  string longtitude = 2;
}

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message MerchantContactCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGMerchantContactReadAll data = 4;
}
//############################################################################################
message MerchantContactReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGMerchantContactReadAll data = 4;
}
//############################################################################################
message MerchantContactReadByIDRequest {
  string id = 1;
}

message MerchantContactReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGMerchantContactReadAll data = 4;
}
//############################################################################################
message MerchantContactUpdateOneRequestQuery {
  string id = 1;
}
message MerchantContactUpdateOneRequest {
  MerchantContactUpdateOneRequestQuery query = 1;
  IGMerchantContactReadAll set = 2;
}
message MerchantContactUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGMerchantContactReadAll data = 4;
}
//############################################################################################
message MerchantContactDeleteOneRequestQuery {
  string id = 1;
}
message MerchantContactDeleteOneRequest {
  MerchantContactDeleteOneRequestQuery query = 1;
}
message MerchantContactDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGMerchantContactReadAll data = 4;
}
//############################################################################################
message IGMerchantContact {
  optional account.common.IAccount reference = 1;
  string phone = 2;
  string email = 3;
  string address = 4;
}

message IGMerchantContactReadAll {
  optional string reference = 1;
  string phone = 2;
  string email = 3;
  string address = 4;
  IGMerchantContactGeo geo = 5;
  SysTime time_created = 8;
  SysTime time_updated = 9;
  SysTime time_deleted = 10;
  bool status = 11;
}