syntax = "proto3";

package product.variant.common;

import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/project/enterprise.organization.project.common.grpc.proto';

import 'product/pos/product/product.pos.product.common.grpc.proto';

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message ProductVariantCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductVariantReadAll data = 4;
}
//############################################################################################
message ProductVariantReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGProductVariantReadAll data = 4;
}
//############################################################################################
message ProductVariantReadByIDRequest {
  string id = 1;
}

message ProductVariantReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductVariantReadAll data = 4;
}
//############################################################################################
message ProductVariantUpdateOneRequestQuery {
  string id = 1;
}
message ProductVariantUpdateOneRequest {
  ProductVariantUpdateOneRequestQuery query = 1;
  IGProductVariant set = 2;
}
message ProductVariantUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductVariantReadAll data = 4;
}
//############################################################################################

message ProductDeleteOneRequestOption {
  optional bool force = 1;
}

message ProductVariantDeleteOneRequestQuery {
  string id = 1;
}
message ProductVariantDeleteOneRequest {
  ProductVariantDeleteOneRequestQuery query = 1;
  optional ProductDeleteOneRequestOption option = 2;
}
message ProductVariantDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductVariantReadAll data = 4;
}
//############################################################################################
message IGProductVariant {
  optional string id = 1;
  optional string reference = 2;
  optional string organization = 3;
  optional string project = 4;
  optional string product = 5;
  optional string code = 6;
  string name = 7;
  optional string description = 8;
  optional int32 price = 9;
  optional string image = 10;
}

message IGProductVariantReadAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional project.common.EnterpriseOrganizationProject project = 4;
  product.common.IGProductAll product = 5;
  optional string code = 6;
  string name = 7;
  optional string description = 8;
  optional int32 price = 9;
  optional string image = 10;
  optional SysTime time_created = 11;
  optional SysTime time_updated = 12;
  optional SysTime time_deleted = 13;
  optional bool status = 14;
}
