syntax = "proto3";

package assets;

import "assets/management/category/assets.management.category.grpc.proto";
import "google/protobuf/empty.proto";


service Assets {
  rpc Create(AssetsCreateRequest) returns (stream AssetsCreateResponse);
  rpc Read(google.protobuf.Empty) returns (stream AssetsReadResponse);
}


message AssetsModel {
  optional string id = 1;
  optional string reference = 2;
  optional category.CategoryModel category = 3;
  optional string name = 4;
  optional string serial_number = 5;
  optional string purchase_date = 6;
  optional string warranty_expires = 7;
  optional string situation = 8;
  optional string time_created = 9;
  optional string time_updated = 10;
  optional bool status = 11;
}

message AssetsCreateRequest {
  optional category.CategoryModel category = 2;
  string name = 3;
  string serial_number = 4;
  optional string purchase_date = 5;
  optional string warranty_expires = 6;
  optional string situation = 7;
}

message AssetsCreateResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  optional AssetsModel data = 4;
}

message AssetsReadResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  repeated AssetsModel data = 4;
}