syntax = "proto3";

package hospitality.patient.type.common;


import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/organization/project/enterprise.organization.project.common.grpc.proto';


//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message PatientTypeCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPatientTypeReadAll data = 4;
}
//############################################################################################
message PatientTypeReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGPatientTypeReadAll data = 4;
}
//############################################################################################
message PatientTypeReadByIDRequest {
  string id = 1;
}

message PatientTypeReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPatientTypeReadAll data = 4;
}
//############################################################################################
message PatientTypeUpdateOneRequestQuery {
  string id = 1;
}
message PatientTypeUpdateOneRequest {
  PatientTypeUpdateOneRequestQuery query = 1;
  IGPatientType set = 2;
}
message PatientTypeUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPatientTypeReadAll data = 4;
}
//############################################################################################
message PatientTypeDeleteOneRequestOption {
  optional bool force = 1;
}
message PatientTypeDeleteOneRequestQuery {
  string id = 1;
}
message PatientTypeDeleteOneRequest {
  PatientTypeDeleteOneRequestQuery query = 1;
  optional PatientTypeDeleteOneRequestOption option = 2;
}
message PatientTypeDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPatientTypeReadAll data = 4;
}
//############################################################################################
message IGPatientType {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  optional string code = 4;
  optional string name = 5;
  optional string description = 6;
}

message IGPatientTypeReadAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional project.common.EnterpriseOrganizationProject project = 4;
  optional string code = 5;
  optional string name = 6;
  optional string description = 7;
  optional SysTime time_created = 8;
  optional SysTime time_updated = 9;
  optional SysTime time_deleted = 10;
  optional bool status = 11;
}
