syntax = "proto3";

package accounting.coa.acct.type;

import 'google/protobuf/empty.proto';
import 'product/accounting/coa/account/type/product.accounting.coa.account.type.common.grpc.proto';

service AccountType {
  rpc Create(common.CoaAccountTypeCreateRequest) returns (stream common.CoaAccountTypeCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (stream common.CoaAccountTypeReadAllResponse);
  rpc ReadByID(common.CoaAccountTypeReadByIDRequest) returns (stream common.IGCoaAccountType);
  rpc UpdateOne(common.CoaAccountTypeUpdateOneRequest) returns (stream common.CoaAccountTypeUpdateOneResponse);
  rpc DeleteOne(common.CoaAccountTypeDeleteOneRequest) returns (stream common.CoaAccountTypeDeleteOneResponse);
}
