syntax = "proto3";

package accounting.coa.acct.type.common;

import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/project/enterprise.organization.project.common.grpc.proto';

//###########################################################################
message CoaAccountTypeCreateRequest {
  optional string reference = 1;
  string organization = 2;
  string project = 3;
  string name = 4;
  optional string description = 5;
}

message CoaAccountTypeCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaAccountTypeAll data = 4;
}
//###########################################################################
message CoaAccountTypeReadByIDRequest {
  string id = 1;
}

message CoaAccountTypeReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaAccountTypeAll data = 4;
}
//###########################################################################
message CoaAccountTypeReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGCoaAccountTypeAll data = 4;
}
//############################################################################################
message CoaAccountTypeUpdateOneRequestQuery {
  string id = 1;
}

message CoaAccountTypeUpdateOneRequestSet {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  string name = 4;
  optional string description = 5;
  bool status = 6;
}

message CoaAccountTypeUpdateOneRequest {
  CoaAccountTypeUpdateOneRequestQuery query = 1;
  CoaAccountTypeUpdateOneRequestSet set = 2;
}

message CoaAccountTypeUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaAccountTypeAll data = 4;
}
//############################################################################################
message CoaAccountTypeDeleteOneRequestOption {
  optional bool force = 1;
}
message CoaAccountTypeDeleteOneRequestQuery {
  string id = 1;
}
message CoaAccountTypeDeleteOneRequest {
  CoaAccountTypeDeleteOneRequestQuery query = 1;
  optional CoaAccountTypeDeleteOneRequestOption option = 2;
}
message CoaAccountTypeDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaAccountTypeAll data = 4;
}
//############################################################################################
//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################

message IGCoaAccountType {
  optional string id = 1;
  optional string reference = 2;
  optional string organization = 3;
  optional string project = 4;
  string name = 5;
  optional string description = 6;
  optional SysTime time_created = 7;
  optional SysTime time_updated = 8;
  optional SysTime time_deleted = 9;
  bool status = 10;
}

message IGCoaAccountTypeAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  organization.common.EnterpriseOrganization organization = 3;
  project.common.EnterpriseOrganizationProject project = 4;
  string name = 5;
  optional string description = 6;
  optional SysTime time_created = 7;
  optional SysTime time_updated = 8;
  optional SysTime time_deleted = 9;
  bool status = 10;
}