syntax = "proto3";

package merchant;

import 'google/protobuf/empty.proto';
import 'product/lms/merchant/product.lms.merchant.common.grpc.proto';

service Merchant {
  rpc Create(common.MerchantCreateRequest) returns (stream common.MerchantCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (stream common.MerchantReadAllResponse);
  rpc ReadByID(common.MerchantReadByIDRequest) returns (stream common.IGMerchant);
  rpc UpdateOne(common.MerchantCreateRequest) returns (stream common.MerchantUpdateOneResponse);
  rpc DeleteOne(common.MerchantDeleteOneRequest) returns (stream common.MerchantDeleteOneResponse);
}
