syntax = "proto3";

package product.common;

import 'core/account/account.common.grpc.proto';
import 'core/enterprise/organization/enterprise.organization.common.grpc.proto';
import 'core/enterprise/organization/project/enterprise.organization.project.common.grpc.proto';

import 'product/pos/product/category/product.pos.product.category.common.grpc.proto';

//###########################################################################
message ProductCreateRequest {
  optional string reference = 1;
  optional string organization = 3;
  optional string project = 4;
  optional string category = 5;
  optional string sku = 6;
  optional string name = 7;
  optional string description = 8;
  optional string image = 9;
}

message ProductCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductAll data = 4;
}
//###########################################################################
message ProductReadByIDRequest {
  string id = 1;
}

message ProductReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductAll data = 4;
}
//###########################################################################
message ProductReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGProductAll data = 4;
}
//############################################################################################
message ProductUpdateOneRequestQuery {
  string id = 1;
}
message ProductUpdateOneRequest {
  ProductUpdateOneRequestQuery query = 1;
  IGProduct set = 2;
}
message ProductUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductAll data = 4;
}
//############################################################################################
message ProductDeleteOneRequestQuery {
  string id = 1;
}
message ProductDeleteOneRequestOption {
  optional bool force = 1;
}

message ProductDeleteOneRequest {
  ProductDeleteOneRequestQuery query = 1;
  optional ProductDeleteOneRequestOption option = 2;
}
message ProductDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductAll data = 4;
}
//############################################################################################
//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################

message IGProduct {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  string category = 4;
  optional string sku = 5;
  string name = 6;
  optional string description = 7;
  optional string image = 8;
}

message IGProductAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional project.common.EnterpriseOrganizationProject project = 4;
  optional product.category.common.IGProductCategoryReadAll category = 5;
  optional string sku = 6;
  string name = 7;
  optional string description = 8;
  optional string image = 9;
  SysTime time_created = 10;
  SysTime time_updated = 11;
  SysTime time_deleted = 12;
  bool status = 13;
}