syntax = "proto3";

package product.common;

import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/project/enterprise.organization.project.common.grpc.proto';

import 'product/pos/product/category/product.pos.product.category.common.grpc.proto';

//###########################################################################
message ProductCreateRequest {
  optional string reference = 1;
  optional string organization = 3;
  optional string project = 4;
  optional string category = 5;
  optional string name = 6;
  optional string description = 7;
  optional string image = 8;
}

message ProductCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProduct data = 4;
}
//###########################################################################
message ProductReadByIDRequest {
  string id = 1;
}

message ProductReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProduct data = 4;
}
//###########################################################################
message ProductReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGProduct data = 4;
}
//############################################################################################
message ProductUpdateOneRequestQuery {
  string id = 1;
}
message ProductUpdateOneRequest {
  ProductUpdateOneRequestQuery query = 1;
  IGProduct set = 2;
}
message ProductUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProduct data = 4;
}
//############################################################################################
message ProductDeleteOneRequestQuery {
  string id = 1;
}
message ProductDeleteOneRequest {
  ProductDeleteOneRequestQuery query = 1;
}
message ProductDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProduct data = 4;
}
//############################################################################################
//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################

message IGProduct {
  optional account.common.IAccount reference = 1;
  optional organization.common.EnterpriseOrganization organization = 2;
  optional project.common.EnterpriseOrganizationProject project = 3;
  product.category.common.IGProductCategory category = 4;
  string name = 5;
  optional string description = 6;
  optional string image = 7;
  SysTime time_created = 8;
  SysTime time_updated = 9;
  SysTime time_deleted = 10;
  bool status = 11;
}