syntax = "proto3";

package account;

import "account/info/account.info.common.grpc.proto";
import "account/credential/account.credential.common.grpc.proto";
import "account/place/account.place.common.grpc.proto";
import "account/account.common.grpc.proto";

service Resources {
  rpc Create(account.common.AccountCreateRequest) returns (stream account.common.AccountCreateResponse);
  rpc ReadAll(account.common.AccountReadRequest) returns (stream account.common.AccountReadResponse);
  rpc ReadByID(account.common.AccountByIDRequest) returns (stream account.common.AccountReadByIDResponse);
  rpc UpdateOne(account.common.AccountPutOneRequest) returns (stream account.common.IAccount);
  rpc DeleteOne(account.common.AccountDeleteOneRequest) returns (stream account.common.IAccount);
}

