syntax = "proto3";

package merchant.category;

import 'product/lms/merchant/category/product.lms.merchant.category.common.grpc.proto';
import "google/protobuf/empty.proto";

service Category {
  rpc Create(common.IGMerchantCategory) returns (stream common.MerchantCategoryCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (stream common.MerchantCategoryReadAllResponse);
  rpc ReadByID(common.MerchantCategoryReadByIDRequest) returns (stream common.MerchantCategoryReadByIDResponse);
  rpc UpdateOne(common.IGMerchantCategory) returns (stream common.MerchantCategoryUpdateOneResponse);
  rpc DeleteOne(common.MerchantCategoryDeleteOneRequest) returns (stream common.MerchantCategoryDeleteOneResponse);
}
