syntax = "proto3";

package accounting.coa.transaction.journal.common;

import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/project/enterprise.organization.project.common.grpc.proto';

import 'product/accounting/coa/transaction/product.accounting.coa.transaction.common.grpc.proto';
import 'product/accounting/coa/account/product.accounting.coa.account.common.grpc.proto';

//###########################################################################
message CoaTransactionJournalCreateRequest {
  optional string reference = 1;
  string organization = 2;
  optional string project = 3;
  optional string transaction = 4;
  string account = 5;
  int32 debit = 6;
  int32 credit = 7;
  optional string memo = 8;
}

message CoaTransactionJournalCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaTransactionJournal data = 4;
}
//###########################################################################
message CoaTransactionJournalReadByIDRequest {
  string id = 1;
}
//###########################################################################
message CoaTransactionJournalReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGCoaTransactionJournal data = 4;
}
//############################################################################################
message CoaTransactionJournalUpdateOneRequestQuery {
  string id = 1;
}

message CoaTransactionJournalUpdateOneRequestSet {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  optional string transaction = 4;
  optional string account = 5;
  optional int32 debit = 6;
  optional int32 credit = 7;
  optional string memo = 8;
}

message CoaTransactionJournalUpdateOneRequest {
  CoaTransactionJournalUpdateOneRequestQuery query = 1;
  CoaTransactionJournalUpdateOneRequestSet set = 2;
}
message CoaTransactionJournalUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaTransactionJournal data = 4;
}
//############################################################################################
message CoaTransactionJournalDeleteOneRequestQuery {
  string id = 1;
}
message CoaTransactionJournalDeleteOneRequest {
  CoaTransactionJournalDeleteOneRequestQuery query = 1;
}
message CoaTransactionJournalDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaTransactionJournal data = 4;
}
//############################################################################################
//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################

message IGCoaTransactionJournal {
  optional account.common.IAccount reference = 1;
  organization.common.EnterpriseOrganization organization = 2;
  project.common.EnterpriseOrganizationProject project = 3;
  optional accounting.coa.transaction.common.IGCoaTransaction transaction = 4;
  optional accounting.coa.acct.common.IGCoaAccount account = 5;
  int32 debit = 6;
  int32 credit = 7;
  optional string memo = 8;
  SysTime time_created = 9;
  SysTime time_updated = 10;
  SysTime time_deleted = 11;
  bool status = 12;
}