syntax = "proto3";

package product.category.common;

import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/organization/project/enterprise.organization.project.common.grpc.proto';

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message ProductCategoryCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductCategoryReadAll data = 4;
}
//############################################################################################
message ProductCategoryReadAllRequestSearch {
  optional string organization = 1;
  optional string project = 2;
}

enum ProductCategoryReadAllRequestSortByEnum {
  DESC = 0;
  ASC = 1;
}

message ProductCategoryReadAllRequest {
  optional ProductCategoryReadAllRequestSearch search = 1;
  optional int32 limit = 2;
  optional int32 skip = 3;
  optional ProductCategoryReadAllRequestSortByEnum sort = 4;
}

message ProductCategoryReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGProductCategoryReadAll data = 4;
}
//############################################################################################
message ProductCategoryReadByIDRequest {
  string id = 1;
}

message ProductCategoryReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductCategoryReadAll data = 4;
}
//############################################################################################
message ProductCategoryUpdateOneRequestQuery {
  string id = 1;
}
message ProductCategoryUpdateOneRequest {
  ProductCategoryUpdateOneRequestQuery query = 1;
  IGProductCategory set = 2;
}
message ProductCategoryUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductCategoryReadAll data = 4;
}
//############################################################################################
message ProductCategoryDeleteOneRequestOption {
  optional bool force = 1;
}
message ProductCategoryDeleteOneRequestQuery {
  string id = 1;
}
message ProductCategoryDeleteOneRequest {
  ProductCategoryDeleteOneRequestQuery query = 1;
  optional ProductCategoryDeleteOneRequestOption option = 2;
}
message ProductCategoryDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGProductCategoryReadAll data = 4;
}
//############################################################################################
message IGProductCategory {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  optional string name = 4;
  optional string description = 5;
}

message IGProductCategoryReadAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional project.common.EnterpriseOrganizationProject project = 4;
  optional string name = 5;
  optional string description = 6;
  optional SysTime time_created = 7;
  optional SysTime time_updated = 8;
  optional SysTime time_deleted = 9;
  optional bool status = 10;
}
