syntax = "proto3";

package product.category;

import 'product/pos/product/category/product.pos.product.category.common.grpc.proto';
import "google/protobuf/empty.proto";

service Category {
  rpc Create(common.IGProductCategory) returns (common.ProductCategoryCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (common.ProductCategoryReadAllResponse);
  rpc ReadByID(common.ProductCategoryReadByIDRequest) returns (common.ProductCategoryReadByIDResponse);
  rpc UpdateOne(common.ProductCategoryUpdateOneRequest) returns (common.ProductCategoryUpdateOneResponse);
  rpc DeleteOne(common.ProductCategoryDeleteOneRequest) returns (common.ProductCategoryDeleteOneResponse);
}
