syntax = "proto3";

package project;

import "enterprise/organization/enterprise.organization.grpc.proto";
import "enterprise/enterprise.contact.grpc.proto";

import "google/protobuf/empty.proto";

service Project {
  rpc Create(EnterpriseOrganizationProjectCreateRequest) returns (stream EnterpriseOrganizationProjectCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (stream EnterpriseOrganizationProjectReadResponse);
}
//###################################################################################
message EnterpriseOrganizationProjectCreateRequest {
  optional string organization = 1;
  optional string name = 2;
  optional string description = 3;
  optional contact.EnterpriseContactCreateRequest contact = 4;
}

message EnterpriseOrganizationProjectCreateResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  optional EnterpriseOrganizationProject data = 4;
}
//###################################################################################
message EnterpriseOrganizationProjectReadResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  repeated EnterpriseOrganizationProject data = 4;
  optional EnterpriseOrganizationProjectReadResponseMetadata metadata = 5;
}

message EnterpriseOrganizationProjectReadResponseMetadata {
  optional int64 count = 1;
}
//###################################################################################
message EnterpriseOrganizationProject {
  optional string reference = 1;
  optional organization.EnterpriseOrganization organization = 2;
  optional string client_secret = 3 [json_name = "client_secret"];
  optional string name = 4;
  optional string description = 5;
  optional contact.EnterpriseContact contact = 6;
  optional string timeCreated = 7;
  optional string timeUpdated = 8;
  optional bool status = 9;
}