syntax = "proto3";

package project;

import "enterprise/project/enterprise.organization.project.common.grpc.proto";
import "google/protobuf/empty.proto";

service Project {
  rpc Create(common.EnterpriseOrganizationProjectCreateRequest) returns (common.EnterpriseOrganizationProjectCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (common.EnterpriseOrganizationProjectReadResponse);
  rpc ReadByID(common.EnterpriseOrganizationProjectReadByIDRequest) returns (common.EnterpriseOrganizationProjectReadByIDResponse);
}
