syntax = "proto3";

package project.common;

import "enterprise/organization/enterprise.organization.common.grpc.proto";
import "enterprise/contact/enterprise.contact.common.grpc.proto";
//###################################################################################
message EnterpriseOrganizationProjectCreateRequest {
  optional string organization = 1;
  optional string name = 2;
  optional string description = 3;
  optional contact.common.EnterpriseContactCreateRequest contact = 4;
}

message EnterpriseOrganizationProjectCreateResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  optional EnterpriseOrganizationProjectCreate data = 4;
}
//###################################################################################
message EnterpriseOrganizationProjectReadResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  repeated EnterpriseOrganizationProject data = 4;
  optional EnterpriseOrganizationProjectReadResponseMetadata metadata = 5;
}

message EnterpriseOrganizationProjectReadResponseMetadata {
  optional int64 count = 1;
}
//############################################################################################
message EnterpriseOrganizationProjectReadByIDRequest {
  string id = 1;
}

message EnterpriseOrganizationProjectReadByIDResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  EnterpriseOrganizationProject data = 4;
}

//############################################################################################
//############################################################################################
message EnterpriseOrganizationProjectReadByOrganizationIDRequest {
  string organization = 1;
}

message EnterpriseOrganizationProjectReadByOrganizationIDResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  repeated EnterpriseOrganizationProject data = 4;
}

//############################################################################################
//############################################################################################
message EnterpriseOrganizationProjectUpdateOneRequest {
  optional string organization = 1;
  optional string name = 2;
  optional string description = 3;
  optional string contact = 4;
}

message EnterpriseOrganizationProjectUpdateOneResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  EnterpriseOrganizationProject data = 4;
}

//############################################################################################

//############################################################################################
message EnterpriseOrganizationProjectDeleteOneRequest {
  optional string id = 1;
}

message EnterpriseOrganizationProjectDeleteOneResponse {
  bool status = 1;
  int64 code = 2;
  string msg = 3;
  EnterpriseOrganizationProject data = 4;
}

//############################################################################################
//###################################################################################
message EnterpriseOrganizationProject {
  optional string id = 1;
  optional string reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional string name = 4;
  optional string description = 5;
  optional contact.common.EnterpriseContact contact = 6;
  optional SysTime time_created = 7;
  optional SysTime time_updated = 8;
  optional bool status = 9;
}


message EnterpriseOrganizationProjectCreate {
  optional string id = 1;
  optional string reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional string name = 4;
  optional string description = 5;
  optional string client_secret = 6;
  optional contact.common.EnterpriseContact contact = 7;
  optional SysTime time_created = 8;
  optional SysTime time_updated = 9;
  optional bool status = 10;
}

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################