syntax = "proto3";

package transaction.items.common;

import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/organization/project/enterprise.organization.project.common.grpc.proto';

import 'product/pos/transaction/product.pos.transaction.common.grpc.proto';
import 'product/pos/product/variant/product.pos.product.variant.common.grpc.proto';

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message TransactionItemsCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGTransactionItemsReadAll data = 4;
}
//############################################################################################
message TransactionItemsReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGTransactionItemsReadAll data = 4;
}
//############################################################################################
message TransactionItemsReadByIDRequest {
  string id = 1;
}

message TransactionItemsReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGTransactionItemsReadAll data = 4;
}
//############################################################################################
message TransactionItemsUpdateOneRequestQuery {
  string id = 1;
}
message TransactionItemsUpdateOneRequest {
  TransactionItemsUpdateOneRequestQuery query = 1;
  IGTransactionItems set = 2;
}
message TransactionItemsUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGTransactionItemsReadAll data = 4;
}
//############################################################################################
message TransactionItemsDeleteOneRequestOption {
  optional bool force = 1;
}
message TransactionItemsDeleteOneRequestQuery {
  string id = 1;
}
message TransactionItemsDeleteOneRequest {
  TransactionItemsDeleteOneRequestQuery query = 1;
  optional TransactionItemsDeleteOneRequestOption option = 2;
}
message TransactionItemsDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGTransactionItemsReadAll data = 4;
}
//############################################################################################
message IGTransactionItems {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  optional string transaction = 4;
  optional string variant = 5;
  optional int32 quantity = 6;
  optional int32 price = 7;
  optional int32 total = 8;
}

message IGTransactionItemsReadAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional project.common.EnterpriseOrganizationProject project = 4;
  transaction.common.IGTransactionAll transaction = 5;
  product.variant.common.IGProductVariantReadAll variant = 6;
  optional int32 quantity = 7;
  optional int32 price = 8;
  optional int32 total = 9;
  optional SysTime time_created = 10;
  optional SysTime time_updated = 11;
  optional SysTime time_deleted = 12;
  optional bool status = 13;
}
