syntax = "proto3";

package hospitality.patient.common;


import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/project/enterprise.organization.project.common.grpc.proto';

import 'product/hospitality/patient/type/product.hospitality.patient.type.common.grpc.proto';

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message PatientCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPatientReadAll data = 4;
}
//############################################################################################
message PatientReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGPatientReadAll data = 4;
}
//############################################################################################
message PatientReadByIDRequest {
  string id = 1;
}

message PatientReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPatientReadAll data = 4;
}
//############################################################################################
message PatientUpdateOneRequestQuery {
  string id = 1;
}
message PatientUpdateOneRequest {
  PatientUpdateOneRequestQuery query = 1;
  IGPatient set = 2;
}
message PatientUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPatientReadAll data = 4;
}
//############################################################################################
message PatientDeleteOneRequestOption {
  optional bool force = 1;
}
message PatientDeleteOneRequestQuery {
  string id = 1;
}
message PatientDeleteOneRequest {
  PatientDeleteOneRequestQuery query = 1;
  optional PatientDeleteOneRequestOption option = 2;
}
message PatientDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPatientReadAll data = 4;
}
//############################################################################################
message IGPatient {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  optional string type = 4;
  optional string account = 5;
}

message IGPatientReadAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional project.common.EnterpriseOrganizationProject project = 4;
  optional hospitality.patient.type.common.IGPatientTypeReadAll type = 5;
  optional account.common.IAccount account = 6;
  optional SysTime time_created = 7;
  optional SysTime time_updated = 8;
  optional SysTime time_deleted = 9;
  optional bool status = 10;
}
