syntax = "proto3";

package enterprise.common;

import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import "enterprise/contact/enterprise.contact.common.grpc.proto";

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message EnterpriseGetClientRequest {
  optional string client_id = 1;
  optional string client_secret = 2;
}

message EnterpriseGetClientResponse {
  optional string id = 1;
  organization.common.EnterpriseOrganization organization = 2;
  optional string name = 3;
  optional string description = 4;
  optional contact.common.EnterpriseContact contact = 5;
  optional SysTime time_created = 6;
  optional SysTime time_updated = 7;
  optional bool status = 8;
}

