syntax = "proto3";

package accounting.coa.transaction.common;

import 'core/account/account.common.grpc.proto';
import 'core/enterprise/organization/enterprise.organization.common.grpc.proto';
import 'core/enterprise/organization/project/enterprise.organization.project.common.grpc.proto';

//###########################################################################
message CoaTransactionCreateRequest {
  optional string reference = 1;
  string organization = 2;
  string project = 3;
  optional string description = 6;
}

message CoaTransactionCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaTransaction data = 4;
}
//###########################################################################
message CoaTransactionReadByIDRequest {
  string id = 1;
}
//###########################################################################
message CoaTransactionReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGCoaTransaction data = 4;
}
//############################################################################################
message CoaTransactionUpdateOneRequestQuery {
  string id = 1;
}

message CoaTransactionUpdateOneRequestSet {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  optional string parent = 4;
  int32 code = 5;
  string name = 6;
  optional string description = 7;
  bool status = 8;
}

message CoaTransactionUpdateOneRequest {
  CoaTransactionUpdateOneRequestQuery query = 1;
  CoaTransactionUpdateOneRequestSet set = 2;
}
message CoaTransactionUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaTransaction data = 4;
}
//############################################################################################
message CoaTransactionDeleteOneRequestQuery {
  string id = 1;
}
message CoaTransactionDeleteOneRequest {
  CoaTransactionDeleteOneRequestQuery query = 1;
}
message CoaTransactionDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGCoaTransaction data = 4;
}
//############################################################################################
//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################

message IGCoaTransaction {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  organization.common.EnterpriseOrganization organization = 3;
  project.common.EnterpriseOrganizationProject project = 4;
  optional string description = 5;
  SysTime time_created = 6;
  SysTime time_updated = 7;
  SysTime time_deleted = 8;
  bool status = 9;
}