syntax = "proto3";

package accounting.coa.transaction;

import 'google/protobuf/empty.proto';
import 'product/accounting/coa/transaction/product.accounting.coa.transaction.common.grpc.proto';

service Transaction {
  rpc Create(common.CoaTransactionCreateRequest) returns (common.CoaTransactionCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (common.CoaTransactionReadAllResponse);
  rpc ReadByID(common.CoaTransactionReadByIDRequest) returns (common.IGCoaTransaction);
  rpc UpdateOne(common.CoaTransactionUpdateOneRequest) returns (common.CoaTransactionUpdateOneResponse);
  rpc DeleteOne(common.CoaTransactionDeleteOneRequest) returns (common.CoaTransactionDeleteOneResponse);
}
