syntax = "proto3";

package credential.common;

import 'core/account/info/account.info.common.grpc.proto';
import 'core/account/place/account.place.common.grpc.proto';

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################

//##################################################################################
message IAccount {
  optional string id = 1;
  optional string reference = 2;
  optional IAccountCredential credential = 3;
  optional info.common.IAccountInfo info = 4;
  optional place.common.IAccountPlace place = 5;
  optional SysTime time_created = 6;
  optional SysTime time_updated = 7;
  optional SysTime time_deleted = 8;
  bool status = 9;
}
//##################################################################################
//##################################################################################
message AccountAuthRequest {
  optional string username = 1;
  optional string password = 2;
}
//##################################################################################

message IAccountCredential {
  optional string id = 1;                  // Document ID (_id in MongoDB)
  optional string reference = 2;          // Preference ObjectId (as string)
  optional string parent = 3;              // Parent ObjectId (as string)
  string email = 4;          // First name as string
  string username = 5;           // Last name as string
  optional string password = 6;
}