syntax = "proto3";

package organization;

import "google/protobuf/empty.proto";
import "core/enterprise/organization/enterprise.organization.common.grpc.proto";

service Organization {
    rpc Create(common.EnterpriseOrganizationCreateRequest) returns (common.EnterpriseOrganizationCreateResponse);
    rpc ReadAll(google.protobuf.Empty) returns (common.EnterpriseOrganizationReadResponse);
    rpc ReadByID(common.EnterpriseOrganizationReadByIDRequest) returns (common.EnterpriseOrganizationReadByIDResponse);
    rpc UpdateOne(common.EnterpriseOrganizationUpdateOneRequest) returns (common.EnterpriseOrganizationUpdateOneResponse);
    rpc DeleteOne(common.EnterpriseOrganizationDeleteOneRequest) returns (common.EnterpriseOrganizationDeleteOneResponse);
}
