syntax = "proto3";

package organization.common;
import "core/enterprise/data/meta/contact/enterprise.data.meta.contact.common.grpc.proto";

//############################################################################################
message SysTime {
    optional int32 unix = 1;
    optional string humanize = 2;
}
//############################################################################################
message EnterpriseOrganizationCreateRequest {
    optional string reference = 1;
    optional string name = 2;
    optional string description = 3;
    optional contact.common.EnterpriseContactCreateRequest contact = 4;
}

message EnterpriseOrganizationCreateResponse {
    bool status = 1;
    int64 code = 2;
    string msg = 3;
    optional EnterpriseOrganization data = 4;
}
//############################################################################################
message EnterpriseOrganizationReadResponse {
    bool status = 1;
    int64 code = 2;
    string msg = 3;
    repeated EnterpriseOrganization data = 4;
    optional EnterpriseOrganizationReadResponseMetadata metadata = 5;
}

message EnterpriseOrganizationReadResponseMetadata {
    optional int64 count = 1;
}
//############################################################################################
message EnterpriseOrganizationReadByIDRequest {
    string id = 1;
}

message EnterpriseOrganizationReadByIDResponse {
    bool status = 1;
    int64 code = 2;
    string msg = 3;
    EnterpriseOrganization data = 4;
}

//############################################################################################
//############################################################################################
message EnterpriseOrganizationUpdateOneRequest {
    optional string organization = 1;
    optional string name = 2;
    optional string description = 3;
    optional string contact = 4;
}

message EnterpriseOrganizationUpdateOneResponse {
    bool status = 1;
    int64 code = 2;
    string msg = 3;
    EnterpriseOrganization data = 4;
}

//############################################################################################

//############################################################################################
message EnterpriseOrganizationDeleteOneRequest {
    optional string id = 1;
}

message EnterpriseOrganizationDeleteOneResponse {
    bool status = 1;
    int64 code = 2;
    string msg = 3;
    EnterpriseOrganization data = 4;
}

//############################################################################################
message EnterpriseOrganization {
    optional string id = 1;
    optional string reference = 2;
    optional string name = 3;
    optional string description = 4;
    optional contact.common.EnterpriseContact contact = 6;
    optional SysTime time_created = 7;
    optional SysTime time_updated = 8;
    optional SysTime time_deleted = 9;
    optional bool status = 10;
}
