syntax = "proto3";

package transaction.meta.payment.common;

import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/project/enterprise.organization.project.common.grpc.proto';

import 'product/pos/transaction/product.pos.transaction.common.grpc.proto';

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message TransactionMetaPaymentCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGTransactionMetaPaymentReadAll data = 4;
}
//############################################################################################
message TransactionMetaPaymentReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGTransactionMetaPaymentReadAll data = 4;
}
//############################################################################################
message TransactionMetaPaymentReadByIDRequest {
  string id = 1;
}

message TransactionMetaPaymentReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGTransactionMetaPaymentReadAll data = 4;
}
//############################################################################################
message TransactionMetaPaymentUpdateOneRequestQuery {
  string id = 1;
}
message TransactionMetaPaymentUpdateOneRequest {
  TransactionMetaPaymentUpdateOneRequestQuery query = 1;
  IGTransactionMetaPayment set = 2;
}
message TransactionMetaPaymentUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGTransactionMetaPaymentReadAll data = 4;
}
//############################################################################################

message ProductDeleteOneRequestOption {
  optional bool force = 1;
}

message TransactionMetaPaymentDeleteOneRequestQuery {
  string id = 1;
}
message TransactionMetaPaymentDeleteOneRequest {
  TransactionMetaPaymentDeleteOneRequestQuery query = 1;
  optional ProductDeleteOneRequestOption option = 2;
}
message TransactionMetaPaymentDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGTransactionMetaPaymentReadAll data = 4;
}
//############################################################################################
message IGTransactionMetaPayment {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  string transaction = 4;
  optional string payment = 5;
  optional string discount = 6;
}

message IGTransactionMetaPaymentReadAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional project.common.EnterpriseOrganizationProject project = 4;
  transaction.common.IGTransactionAll transaction = 5;
  optional string payment = 6;
  optional string discount = 7;
  optional SysTime time_created = 8;
  optional SysTime time_updated = 9;
  optional SysTime time_deleted = 10;
  optional bool status = 11;
}
