syntax = "proto3";

package product.variant;

import 'product/pos/product/variant/product.pos.product.variant.common.grpc.proto';
import "google/protobuf/empty.proto";

service Variant {
  rpc Create(common.IGProductVariant) returns (common.ProductVariantCreateResponse);
  rpc ReadAll(google.protobuf.Empty) returns (common.ProductVariantReadAllResponse);
  rpc ReadByID(common.ProductVariantReadByIDRequest) returns (common.ProductVariantReadByIDResponse);
  rpc UpdateOne(common.ProductVariantUpdateOneRequest) returns (common.ProductVariantUpdateOneResponse);
  rpc DeleteOne(common.ProductVariantDeleteOneRequest) returns (common.ProductVariantDeleteOneResponse);
}
