syntax = "proto3";

package merchantInfo;

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################

message IGMerchantInfo {
  string name = 1;
  string description = 2;
  string logo = 3;
  SysTime time_created = 8;
  SysTime time_updated = 9;
  SysTime time_deleted = 10;
  bool status = 11;
}