syntax = "proto3";

package merchant.info.common;

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message MerchantInfoCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGMerchantInfoReadAll data = 4;
}
//############################################################################################
message MerchantInfoReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGMerchantInfoReadAll data = 4;
}
//############################################################################################
message MerchantInfoReadByIDRequest {
  string id = 1;
}

message MerchantInfoReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGMerchantInfoReadAll data = 4;
}
//############################################################################################
message MerchantInfoUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGMerchantInfoReadAll data = 4;
}
//############################################################################################
message MerchantInfoDeleteOneRequest {
  string id = 1;
}
message MerchantInfoDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGMerchantInfoReadAll data = 4;
}
//############################################################################################
message IGMerchantInfo {
  string name = 1;
  string description = 2;
  string logo = 3;
}

message IGMerchantInfoReadAll {
  string name = 1;
  string description = 2;
  string logo = 3;
  SysTime time_created = 8;
  SysTime time_updated = 9;
  SysTime time_deleted = 10;
  bool status = 11;
}