syntax = "proto3";

package promo.campaign.common;

import 'account/account.common.grpc.proto';
import 'enterprise/organization/enterprise.organization.common.grpc.proto';
import 'enterprise/project/enterprise.organization.project.common.grpc.proto';

//############################################################################################
message SysTime {
  optional int32 unix = 1;
  optional string humanize = 2;
}
//############################################################################################
message PromoCampaignCreateResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPromoCampaignReadAll data = 4;
}
//############################################################################################
message PromoCampaignReadAllResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  repeated IGPromoCampaignReadAll data = 4;
}
//############################################################################################
message PromoCampaignReadByIDRequest {
  string id = 1;
}

message PromoCampaignReadByIDResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPromoCampaignReadAll data = 4;
}
//############################################################################################
message PromoCampaignUpdateOneRequestQuery {
  string id = 1;
}
message PromoCampaignUpdateOneRequest {
  PromoCampaignUpdateOneRequestQuery query = 1;
  IGPromoCampaign set = 2;
}
message PromoCampaignUpdateOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPromoCampaignReadAll data = 4;
}
//############################################################################################
message PromoCampaignDeleteOneRequestOption {
  optional bool force = 1;
}
message PromoCampaignDeleteOneRequestQuery {
  string id = 1;
}
message PromoCampaignDeleteOneRequest {
  PromoCampaignDeleteOneRequestQuery query = 1;
  optional PromoCampaignDeleteOneRequestOption option = 2;
}
message PromoCampaignDeleteOneResponse {
  bool status = 1;
  int32 code = 2;
  string msg = 3;
  IGPromoCampaignReadAll data = 4;
}
//############################################################################################
message IGPromoCampaign {
  optional string reference = 1;
  optional string organization = 2;
  optional string project = 3;
  optional string name = 4;
  optional string description = 5;
}

message IGPromoCampaignReadAll {
  optional string id = 1;
  optional account.common.IAccount reference = 2;
  optional organization.common.EnterpriseOrganization organization = 3;
  optional project.common.EnterpriseOrganizationProject project = 4;
  optional string name = 5;
  optional string description = 6;
  optional SysTime time_created = 7;
  optional SysTime time_updated = 8;
  optional SysTime time_deleted = 9;
  optional bool status = 10;
}
